### PR TITLE
Clickable map with css addition

### PR DESCRIPTION
**Pull request by evrkusd**

### CODE REVIEW

**Comment by MoralCode** [comment]
turns out HTML actually has a [`<map>` tag](https://caniuse.com/mdn-html_elements_map) explicitly for clickable image maps

**Comment by MoralCode** [comment]
i have created a new branch based off of this one at https://github.com/MoralCode/FindYourVaccine.org/tree/clickable-map @evrkusd could you maybe give me contributor access to your fork so i can push my changes to your repo and make them part of this PR?

all that should to be done is adding the xlinks around the paths for each state in the svg file and (hopefully) throwing it in a `<map>` 
```
<a xlink:href="./CA">
<path id="CA-AB" d="M1321.652,944…
</a>
```

logging off for the night but ill see what i can do later

**Comment by evrkusd** [comment]
hey @MoralCode I think I added you to my fork but I'm not 100% sure. If I didn't, can you let me know how to give you access?

**Comment by MoralCode** [comment]
@evrkusd I ended up just making a new PR #10 since my changes were based on doing things a different way than you did in this PR and I didn't want to just take over your PR and immediately un-do all your work.

**Pull request closed without merging**
